server:
  port: ${PORT:9090}

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-cita
          uri: ${MS_CITA_URL:http://localhost:8080}
          predicates:
            - Path=/api/citas/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-cliente
          uri: ${MS_CLIENTE_URL:http://localhost:8081}
          predicates:
            - Path=/api/clientes/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-factura
          uri: ${MS_FACTURA_URL:http://localhost:8082}
          predicates:
            - Path=/api/facturas/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-inventario
          uri: ${MS_INVENTARIO_URL:http://localhost:8083}
          predicates:
            - Path=/api/inventarios/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-mecanico
          uri: ${MS_MECANICO_URL:http://localhost:8084}
          predicates:
            - Path=/api/mecanicos/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-notificacion
          uri: ${MS_NOTIFICACION_URL:http://localhost:8085}
          predicates:
            - Path=/api/notificaciones/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-producto
          uri: ${MS_PRODUCTO_URL:http://localhost:8086}
          predicates:
            - Path=/api/productos/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-proveedor
          uri: ${MS_PROVEEDOR_URL:http://localhost:8087}
          predicates:
            - Path=/api/proveedores/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-reparacion
          uri: ${MS_REPARACION_URL:http://localhost:8088}
          predicates:
            - Path=/api/reparaciones/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

        - id: ms-vehiculo
          uri: ${MS_VEHICULO_URL:http://localhost:8089}
          predicates:
            - Path=/api/vehiculos/**
          filters:
            - AddRequestHeader=X-Gateway-Source, TallerGateway

      default-filters:
        - AddResponseHeader=X-Powered-By, TallerMecanico-Gateway

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
