server:
  port: ${PORT:8087}

spring:
  application:
    name: ms-proveedor
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_taller?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
